### ISSUE TITLE
博主可以发点IDA的调试教程

### ISSUE THREAD

**Issue by topcss** [XhyEax/XhyEax.github.io#1]
如题，博主可以在b站上发点IDA的视频教程。

**Comment by XhyEax** [comment]
视频教程就不必了吧，IDA自己多用就会了。主要就是查看伪C代码，下断点动态调试还有修改指令。

**Comment by topcss** [comment]
网上这方面视频教程比较少，博主录制的话应该会让很多人受益，也会很受欢迎的。
