### ISSUE TITLE
大佬你好

### ISSUE THREAD

**Issue by PShocker** [XhyEax/XhyEax.github.io#2]
定制SELinux规则 允许app访问内核模块
这篇文章里,其实可以不用搞一个模块和命令行
可以直接把sepolicy编译到magiskinit里,甚至模块也可以和magisk弄到一起.
可以参考我的文章:
[Magisk内嵌驱动模块且启动加载](https://pshocker.github.io/2022/08/05/Magisk%E5%86%85%E5%B5%8C%E9%A9%B1%E5%8A%A8%E6%A8%A1%E5%9D%97%E4%B8%94%E5%90%AF%E5%8A%A8%E5%8A%A0%E8%BD%BD/)

**Comment by XhyEax** [comment]
好的，我知道可以通过重编译magisk来内置selinux规则。
就是因为不打算动magisk（自编译的稳定性感觉不如原生），才采用模块加载的方式。

后续我把你的文章附上，多谢补充了。
